from hexaplot import HexapodPlot
from hexapod import VirtualHexapod

FRONT_LENGTH = 60
SIDE_LENGTH = 60
MID_LENGTH = 90
HIP_LENGTH = 60
KNEE_LENGTH = 60
ANKLE_LENGTH = 60

BASE_HEXAPOD = VirtualHexapod(HIP_LENGTH, KNEE_LENGTH, ANKLE_LENGTH, FRONT_LENGTH, MID_LENGTH, SIDE_LENGTH)
BASE_HEXAPLOT = HexapodPlot(BASE_HEXAPOD)
